"""Regenerate THIRD_PARTY_NOTICES.md from the runtime lock.

Hand-maintained notices drift the moment a lock changes, and a stale notice
file is worse than none: it asserts something specific and false. So the file
is generated, and tests/test_licenses.py fails when it no longer matches the
lock it claims to describe.
"""

from __future__ import annotations

import argparse
import importlib.metadata as metadata
import re
import sys
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
NOTICES = ROOT / "THIRD_PARTY_NOTICES.md"
LOCK = ROOT / "requirements.lock"

#: Licenses we are willing to ship. Anything else must be a deliberate,
#: recorded decision rather than a silent addition.
ALLOWED_LICENSES = {
    "Apache-2.0",
    "Apache Software License v2",
    "BSD-3-Clause",
    "BSD License",
    "MIT",
    "MIT OR Apache-2.0",
    "MPL-2.0",
    "PSF-2.0",
    "Dual License",
}

_PIN = re.compile(r"^([A-Za-z0-9._-]+)==([^;]+)")


def pinned_packages(lock_path: Path = LOCK) -> list[tuple[str, str, str]]:
    """Return (name, version, marker) for every pin in the runtime lock."""
    out: list[tuple[str, str, str]] = []
    for line in lock_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("-r"):
            continue
        match = _PIN.match(line)
        if not match:
            continue
        marker = line.split(";", 1)[1].strip() if ";" in line else ""
        out.append((match.group(1), match.group(2).strip(), marker))
    return sorted(out, key=lambda r: r[0].lower())


def license_of(name: str) -> str:
    """Best available license string for an installed distribution."""
    try:
        meta = metadata.metadata(name)
    except metadata.PackageNotFoundError:
        return "UNKNOWN (not installed in this environment)"
    declared = meta.get("License-Expression") or meta.get("License") or ""
    if declared and len(declared) <= 40:
        return declared.strip()
    classifiers = [
        c.split(" :: ")[-1]
        for c in (meta.get_all("Classifier") or [])
        if c.startswith("License ::")
    ]
    return "; ".join(classifiers) if classifiers else "UNKNOWN"


def render(rows: Iterable[tuple[str, str, str, str]]) -> str:
    lines = [
        "# Third-party notices",
        "",
        "Glassbox depends on the packages below. Each is used under its own",
        "license, reproduced by its project; this file records what is shipped and",
        "under which terms. It is generated by `tools/build_notices.py` from",
        "`requirements.lock` -- edit the lock, then regenerate.",
        "",
        "| Package | Version | License |",
        "| --- | --- | --- |",
    ]
    for name, version, license_name, marker in rows:
        suffix = f" _{marker}_" if marker else ""
        lines.append(f"| `{name}` | {version}{suffix} | {license_name} |")
    lines += [
        "",
        "## Ideas and interfaces",
        "",
        "The official Alpaca repositories were read during design and are cited",
        "rather than copied:",
        "",
        "- `alpaca-py` (Apache-2.0) is the sole programmatic Trading/Data SDK.",
        "- The official Alpaca MCP server (MIT) was inspected for its tool surface.",
        "  No MCP integration is claimed here; see README for what is demonstrated.",
        "- Alpaca Skills (Apache-2.0) are prose guidance. Any wording adapted from",
        "  them belongs in operator documentation with attribution, never as",
        "  executable policy.",
        "",
        "Four third-party trading projects were reviewed during the design audit.",
        "No code, UI, prompt, or asset from any of them is present in this",
        "repository. Two of the four carry licenses that would forbid such reuse",
        "(one is unlicensed and self-described as proprietary; one is PolyForm",
        "Noncommercial 1.0.0), which is why every pattern here was implemented",
        "independently from the deterministic contracts in `glassbox/`.",
        "",
    ]
    return "\n".join(lines)


def build() -> str:
    rows = [(n, v, license_of(n), m) for n, v, m in pinned_packages()]
    return render(rows)


def missing_unconditional_packages() -> list[str]:
    """Pinned packages that are absent but should not be.

    A package with an environment marker -- `exceptiongroup` on 3.11+, the
    win32-only ones -- is legitimately absent here. An unconditional pin that
    is missing means the notices would record "UNKNOWN (not installed)" for a
    dependency we actually ship, which is how a legal document ends up
    describing the machine that generated it rather than the software.
    """
    absent: list[str] = []
    for name, _version, marker in pinned_packages():
        if marker:
            continue
        try:
            metadata.metadata(name)
        except metadata.PackageNotFoundError:
            absent.append(name)
    return absent


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args(argv)

    absent = missing_unconditional_packages()
    if absent:
        print(
            "refusing to touch the notices: these pinned packages are not "
            f"installed, so their licenses would be recorded as UNKNOWN: {', '.join(absent)}\n"
            "install the full lock first: pip install -r requirements-dev.lock",
            file=sys.stderr,
        )
        return 2

    content = build()
    if args.check:
        current = NOTICES.read_text(encoding="utf-8") if NOTICES.exists() else ""
        if current != content:
            print("THIRD_PARTY_NOTICES.md is stale; run tools/build_notices.py", file=sys.stderr)
            return 1
        print("notices are current")
        return 0

    NOTICES.write_text(content, encoding="utf-8")
    print(f"wrote {NOTICES.name}: {len(pinned_packages())} packages")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
